SELECT USER
FROM DUAL;
--==>> HR


--○ 세 개 이상의 테이블 조인(JOIN)

-- 형식1(SQL 1992 CODE)
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1, 테이블명2, 테이블명3
WHERE 테이블명1.컬럼명1 = 테이블명2.컬럼명1
  AND 테이블명2.컬럼명2 = 테이블명3.컬럼명2;

-- 형식2(SQL 1999 CODE)
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1 JOIN 테이블명2
ON 테이블명1.컬럼명1 = 테이블명2.컬럼명1
        JOIN 테이블명3
        ON 테이블명2.컬럼명2 = 테이블명3.컬럼명2;


--○ HR 계정 소유 테이블 또는 뷰 목록 조회
SELECT *
FROM TAB;
--==>>
/*
COUNTRIES	        TABLE	
DEPARTMENTS	        TABLE	
EMPLOYEES	        TABLE	
EMP_DETAILS_VIEW	VIEW	
JOBS	            TABLE	
JOB_HISTORY	        TABLE	
LOCATIONS	        TABLE	
REGIONS	            TABLE	
*/


--○ HR.JOBS, HR.EMPLOYEES, HR.DEPARTMENTS 테이블을 대상으로
--   직원들의 정보를 FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME 
--   항목을 조회한다.

SELECT COUNT(*)  
FROM EMPLOYEES;  --> 제일 큰 값이므로 첫 조건절(상위)에 있어야 함
--==>> 107


--○ 각각의 테이블 정보(컬럼명, 데이터 유형) 조회
DESC JOBS;
DESC EMPLOYEES;
DESC DEPARTMENTS;

--○ 방법1. SQL 1992 CODE
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME 
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D
WHERE E.JOB_ID = J.JOB_ID(+)
  AND J.MANAGER_ID = D.MANAGER_ID(+);


--○ 방법2. SQL 1999 CODE
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME 
FROM EMPLOYEES E LEFT JOIN JOBS J
  ON E.JOB_ID = J.JOB_ID
          LEFT JOIN DEPARTMENTS D
          ON J.MANAGER_ID = D.MANAGER_ID; 


--○ EMPLOYEES, DEPARTMENTS, JOBS, LOCATIONS, COUNTRIES, REGIONS 테이블을 대상으로
--   직원들의 정보를 다음과 같이 조회한다.
--   FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME
--   , CITY, COUNTRY_NAME, REGION_NAME

DESC EMPLOYEES;
DESC DEPARTMENTS;
DESC JOBS;
DESC LOCATIONS;
DESC COUNTRIES;
DESC REGIONS;


SELECT COUNT(*)
FROM EMPLOYEES;
--==>> 107   
--> 부모 테이블로 기준이 됨

--○ 방법1. SQL 1992 CODE
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D, LOCATIONS L, COUNTRIES C,  REGIONS R
WHERE E.JOB_ID =  J.JOB_ID
  AND E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
  AND D.LOCATION_ID = L.LOCATION_ID(+)
  AND L.COUNTRY_ID = C.COUNTRY_ID(+)
  AND C.REGION_ID  = R.REGION_ID(+);  


--○ 방법2. SQL 1999 CODE
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM EMPLOYEES E LEFT JOIN JOBS J 
ON E.JOB_ID =  J.JOB_ID
        LEFT JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                    LEFT JOIN LOCATIONS L
                    ON D.LOCATION_ID = L.LOCATION_ID
                           LEFT JOIN COUNTRIES C
                           ON L.COUNTRY_ID = C.COUNTRY_ID
                                  LEFT JOIN REGIONS R
                                  ON C.REGION_ID  = R.REGION_ID;  



